# Generated by Django 3.2 on 2023-06-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(blank=True, choices=[('user', 'пользователь'), ('moderator', 'модератор'), ('admin', 'администратор')], default='user', verbose_name='Пользовательская роль'),
        ),
    ]
